### ISSUE TITLE
Progress reports due weekly

### ISSUE THREAD

**Issue by wwwidmer** [wwwidmer/CAPSTONE2015#15]
Detailed list of what everyone does

**Comment by wwwidmer** [comment]
What we've done:
Database schema done but not implemented.
Index.html is up but no functionality
Wireframe drawn up
Necessary frameworks and tools installed / uploaded

**Comment by ShehryarKh** [comment]
we will continue in class, and assign roles to everyone form there, i've been super busy so wasnt able to do much this weekend, but my work schedule has been cleared out and now im more free time, so i will be working on it more.-khan

```
 On Tuesday, June 9, 2015 10:13 AM, william widmer <notifications@github.com> wrote:
```

 What we've done:
Database schema done but not implemented.
Index.html is up but no functionality
Wireframe drawn up
Necessary frameworks and tools installed / uploaded—

**Comment by qgjevukaj** [comment]
I picked up couple domains for the website...... I believe I found the one............

**Comment by wwwidmer** [comment]
Someone can volunteer to write up the written report for Thursday.

**Comment by wwwidmer** [comment]
I cannot open google documents at work so here is my portion to be added to the google Doc.

Week of 6/9
William - Fullstack Developer / Project Manager
I set up our Github page and gave a crash course on using git to branch, merge, pull, checkout, and revert. 
We've defined database schema together as a group. Qendrim and I wrote into the Models file and defined the relationships between database tables.
I implemented the Python Code to render URL requests to specific HTML pages. So far the URL routes configured are Index, Menu/ID, Food/ID, and search/results. These are referred to as 'Views'.
I wrote the javascript/jquery to accept a search string from an input box and open Search.html. 
I wrote the functions for search in Python to use define SQL querys for searching these items on certain fields. This was recycled code from a previous project of mine.
I uploaded Jquery / Bootstrap frameworks to the server and defined their Static URLs. This is the server configuration for displaying non-user uploaded files.

Next week:
- We will work on HTML together. The aim is to have a user interface to stroll around the site and give a feel of hte layout. We are not aiming for a modern GUI at this time that will be after feature complete.
  The above includes CSS and Javascript.
- We want to try to incorporate an embedded system however at this point it seems detrimental to the original project idea. This may very well become a small afterthought that doesn't work (ie - look we tried) and I don't have any money for a raspberry pi anyway. 

I will continue working on Views for the first bullet to be complete and occasionally dive into the frontend. 
I will write a Form template for adding a Review to each FoodItem however this is not the primary goal.
I will write unit tests for each Model.

**Comment by wwwidmer** [comment]
Week of 6/15
William - Fullstack / Project Manager
Added views and HTML for displaying menus
Coded Form template for adding Reviews to Menus
Determined URL routing for Menus / Foods - grabs data from Database using a numerical Key ID
Coded into Models.py a method to average all Reviews for a food
Wrote basic set up for tests, functionality for later
New images for displaying Average Review (stars)
Added new CSS style sheets

Upcoming weeks:
Image Upload for Items/Reviews/Menus
Model/Database Schema Review
Google Maps API for browsing Menus by Location
UI for Menus (Food types, course, etc)
Update Search by Keyword

**Comment by RichardHung** [comment]
The pages I save as rar binary file is in my branch. I used many css class. Should I remove them?

**Comment by wwwidmer** [comment]
@RichardHung Why are they saved as binary files? And which files? 
You just need to update your branch with the files as is there is no need to zip, save as a raw binary, or alter their extensions. Git handles all file uploading to the server. We can't keep track of files if they're different from one branch to the next. You can add new files but do not save them as different extensions or rename them without an explicit Commit message saying so. Do not compress multiple files into one and upload them we'll never be able to tell what was changed / committed. 

We changed the policy of master merging but everyone should be working on their respective branches. You still need to push your branch to remote (github) so we can all view each others code. 
I see no one has updated their branches so either delete your old remote branch or push your local's changes.
Also either comment your weekly progress here or add to the Google Doc - If you haven't done that do that before tomorrow morning! (Or at least leave a note saying you're going to have it written before class)

**Comment by qgjevukaj** [comment]
weekly progress should be moved to thursdays...

**Comment by wwwidmer** [comment]
They're due on Tuesdays in class

**Comment by wwwidmer** [comment]
Just need to make sure I get this:

We hand in a Group write up on Tuesdays and Thursdays we hand in an individual?

That said this weeks group write up should focus on google maps, AJAX, and image uploading.

**Comment by qgjevukaj** [comment]
image uploading is done.... not pushed yet
-user is able to upload an image for their review

**Comment by wwwidmer** [comment]
How is everyone's progress reports? They're due Thursday(wednesday) and we should start compiling into the main google doc. As usual I can't access google docs at work - we should add them in chronologically together.
