### ISSUE TITLE
Wireframes for GUI

### ISSUE THREAD

**Issue by wwwidmer** [wwwidmer/CAPSTONE2015#19]
Someone make a wireframe and a sitemap for the app. IE Draw out each pages look and feel then create a directed graph to show which pages link to each other

**Comment by qgjevukaj** [comment]
Looking into this -QG

**Comment by ShehryarKh** [comment]
wireframe, can we sketch it out on word document, or should we go into details. We might want to talk as a group about the design, there is something called hotgloo that is free for 15 days and lets you design a website 

```
 On Monday, June 8, 2015 2:34 PM, QGjevukaj <notifications@github.com> wrote:
```

 Looking into this -QG—

**Comment by qgjevukaj** [comment]
I've begun working on a sketch utilizing balsamiq which I'll present tomorrow.
Based on the ideas and concepts for the site that we spoke about, I've put together
an example of what the site could look like and the various functions that would need to be implemented to support such functionality portrayed in my sketch. You guys could adjust and debate on it tomorrow

**Comment by qgjevukaj** [comment]
I've attached a pdf to the master branch containing the wireframe sketch

**Comment by wwwidmer** [comment]
The pdf looks great. Good job. We'll talk more on it later.
