### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by wwwidmer** [wwwidmer/CAPSTONE2015#25]
Edit models.py with correct information and fields. Determine what exactly 'types' are and how they relate to the fooditem class. Document how to migrate database correctly. Set default fields where needed.

**Comment by wwwidmer** [comment]
All Models need 'Enabled/Active' boolean field.

**Comment by qgjevukaj** [comment]
Looking into it, it will take a bit time I;m testing against models views urls and javascript to see
how they are functioning together.

**Comment by ShehryarKh** [comment]
guys we only showing restaurants that are in our database? correct? thats the best way to go about it?-Khan 

```
 On Wednesday, June 10, 2015 11:53 AM, QGjevukaj <notifications@github.com> wrote:
```

 Looking into it, it will take a bit time I;m testing against models views urls and javascript to see
how they are functioning together.—

**Comment by qgjevukaj** [comment]
yes that is correct for the moment,

**Comment by wwwidmer** [comment]
Google maps will allow us to show lots of restaurants. We can reference what we have and what we don't somehow (probably using JSON data). An idea would be to have google maps show everything it has then we can follow up with a link and if we have no menu for that restaurant just display to user that we don't have that.

You may want to move this discussion to the Google Maps issue.

**Comment by wwwidmer** [comment]
I think we'll have a lot more fields in each model now that we're incorporating the google maps api. Things like lat and long or other fields in the JSON/XML we get from google.

**Comment by qgjevukaj** [comment]
I'll need more details from shehryar if a new model is needed, at this point the main data has been outlined & organized for the database which we'll go over today and from there we will move to developing functions to access this data and manipulate it. I've created an outline of the database schema and how the data is been passed please see in the google doc

**Comment by qgjevukaj** [comment]
see my branch root for the Database Schema if you cannot reach the document

**Comment by wwwidmer** [comment]
We have to talk about the relationships I think I may be confusing myself though.

Good work though, you seem to be getting the hang of Python.
