### ISSUE TITLE
Write Tests

### ISSUE THREAD

**Issue by wwwidmer** [wwwidmer/CAPSTONE2015#27]
Test.py for functions and classes. Unit test certain functionality that isn't straight forward.

**Comment by wwwidmer** [comment]
I've assigned this to myself however I encourage everyone to take a look and add tests themselves. They're really straight forward - You'll need to use Assert commands so take a look at the python or django docs.

**Comment by ShehryarKh** [comment]
i got the map to work, it displays a marker to where the person is located. i want to push the html file, only think im a little confused about how you(william) wanted me to separate all the script form html, i was having a hard time getting it to function like that. -Khan 


     On Friday, June 12, 2015 1:49 PM, william widmer <notifications@github.com> wrote:
   

 I've assigned this to myself however I encourage everyone to take a look and add tests themselves. They're really straight forward - You'll need to use Assert commands so take a look at the python or django docs. —

**Comment by wwwidmer** [comment]
Becoming fairly difficult to maintain the tests because the models are changing almost weekly. I'll try to update them as I think we've hit a limit on changing schema for the time being.
