### ISSUE TITLE
google api

### ISSUE THREAD

**Issue by ShehryarKh** [wwwidmer/CAPSTONE2015#32]
so im running into issues with the google api, im going to need some help with it. My next goal is to have a keyterm say "starbucks" and the map will display your location as a marker( which is working) and the near by starbucks should appear. This issue i am having a hard time with, i tired multiple things, but it would not work. So i may require help. will talk more about it in class tomorrow.

**Comment by QGjevukaj** [comment]
weekly progress should really be moved to thursdays...

**Comment by qgjevukaj** [comment]
The real question is if you're able to get a user input to approximate their location (which I saw previously last time that you could return their latitude and longitude, and in the code it defines its own search box, isn't their a way to pass a string of characters to that search box from outside?

**Comment by wwwidmer** [comment]
Try to centralize each topic in one thread - I'll close the other one.

As for the issues - Is there code we can see right now / pushed to your branch?

**Comment by qgjevukaj** [comment]
William you have blown my mind with what you've implemented
