### ISSUE TITLE
Model Schema Rewrite

### ISSUE THREAD

**Issue by wwwidmer** [wwwidmer/CAPSTONE2015#33]
We're adding some new fields to each model -
things like imagefields and extra content.
@QGjevukaj I found this page in the documentation that may help
https://docs.djangoproject.com/en/1.8/topics/db/aggregation/

**Comment by qgjevukaj** [comment]
Okay thank you :). this logic of aggregation might be doing me a couple favors tonight

**Comment by qgjevukaj** [comment]
Looking into individual user uploads next for reviews
