### ISSUE TITLE
front end

### ISSUE THREAD

**Issue by ShehryarKh** [wwwidmer/CAPSTONE2015#34]
shehryar- working on front end.
Richard, I started coding for front end, let me know if you have something that i can use, if not i will be creating few pages on my own, and you and edit them. you can contact me and share some code with me so we can actually make faster progress.

**Comment by RichardHung** [comment]
I've some page in my branch which I'm trying to convert them into bootstrap.
The css and js from online source would make different result than the one in assets file.
I am trying to make the button in index file work. It doesn't work for me in FireFox Chrome and IE even though I use copy & past.

**Comment by wwwidmer** [comment]
we've got a base going now so tomorrow we can go to the library and talk about the site map. We can get that down pretty quickly.
