### ISSUE TITLE
Production issue regarding auto-generating menus, gids...

### ISSUE THREAD

**Issue by qgjevukaj** [wwwidmer/CAPSTONE2015#37]
Whether you guys want to spend time on this or not I'll take a look but, if you go to the url path for a menu that is autogenerated by clicking on the marker icon

e.g. menus/gid/menuName

by default if this data does not it will create it but, this means that anything you type in the gid and menuName field for url will be created.

e.g. menus/10/Starbucks 
e.g.menus/1999919929/Starbucks
e.g. menus/1/CardBucks/

if you get the point.
this needs to be blocked and only limited to clicking on a marker from google maps

**Comment by wwwidmer** [comment]
ideally the ajax method in views.py would be the way to go about doing this. ie we send an ajax request to menus/gid/menuname and that handles it instead. (we can pad a password into the ajax request so only someone with certain rights can add menus).

**Comment by wwwidmer** [comment]
Urls.py needs an update to allow words differently.
right now if you menus/number/fast food - only 'fast' is saved so ideally we need
menus/number/fast-food - so a method to add in dashes where there are spaces and a deciphering method to read dashes as spaces. shouldn't be too hard with regexs.
